litmustojson/urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'litmustojson.views.home', name='home'),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

litmustojson/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.

from django.db import models

class Product(models.Model):
    product_id = models.IntegerField(primary_key=True)
    name = models.CharField(unique=True, max_length=192)
    iconpath = models.CharField(max_length=765, blank=True)
    enabled = models.IntegerField(null=True, blank=True)
    creator_id = models.IntegerField()
    last_updated = models.DateTimeField()
    creation_date = models.DateTimeField()

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = u'products'

class Branch(models.Model):
    branch_id = models.IntegerField(primary_key=True)
    product = models.ForeignKey(Product)
    name = models.CharField(max_length=192)
    detect_regexp = models.CharField(max_length=765, blank=True)
    enabled = models.IntegerField(null=True, blank=True)
    creator_id = models.IntegerField()
    last_updated = models.DateTimeField()
    creation_date = models.DateTimeField()

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = u'branches'






class Testgroup(models.Model):
    testgroup_id = models.IntegerField(primary_key=True)
    product = models.ManyToManyField(Product, through='GroupProductMap')
    name = models.CharField(max_length=192)
    enabled = models.IntegerField(null=True, blank=True)
    branch = models.ForeignKey(Branch)
    creator_id = models.IntegerField()
    last_updated = models.DateTimeField()
    creation_date = models.DateTimeField()

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = u'testgroups'



class Subgroup(models.Model):
    subgroup_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=192)
    enabled = models.IntegerField(null=True, blank=True)
    product = models.ForeignKey(Product)
    branch = models.ForeignKey(Branch)
    creator_id = models.IntegerField()
    last_updated = models.DateTimeField()
    creation_date = models.DateTimeField()
    testgroup = models.ManyToManyField(Testgroup, through='SubgroupTestgroup')

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = u'subgroups'

class Testcase(models.Model):
    testcase_id = models.IntegerField(primary_key=True)
    summary = models.CharField(max_length=765)
    details = models.TextField(blank=True)
    community_enabled = models.IntegerField(null=True, blank=True)
    format_id = models.IntegerField()
    regression_bug_id = models.IntegerField(null=True, blank=True)
    steps = models.TextField(blank=True)
    expected_results = models.TextField(blank=True)
    author_id = models.IntegerField()
    creation_date = models.DateTimeField()
    last_updated = models.DateTimeField()
    version = models.IntegerField()
    enabled = models.IntegerField()
    product = models.ForeignKey(Product)
    branch = models.ForeignKey(Branch)
    subgroup = models.ManyToManyField(Subgroup, through='TestcaseSubgroup')

    def __unicode__(self):
        return self.summary

    class Meta:
        db_table = u'testcases'



class GroupProductMap(models.Model):
    group = models.ForeignKey(Testgroup)
    product = models.ForeignKey(Product)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = u'group_product_map'


class SubgroupTestgroup(models.Model):
    subgroup = models.ForeignKey(Subgroup)
    testgroup = models.ForeignKey(Testgroup)
    sort_order = models.IntegerField()

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = u'subgroup_testgroups'


class TestcaseSubgroup(models.Model):
    testcase = models.ForeignKey(Testcase)
    subgroup = models.ForeignKey(Subgroup)
    sort_order = models.IntegerField()

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = u'testcase_subgroups'

litmustojson/forms.py
from django import forms
from models import Product, Branch, Testgroup
from django.forms import ChoiceField, MultipleChoiceField

class HomeForm(forms.Form):

    product = forms.ModelChoiceField(queryset=Product.objects.all().order_by('name'))
    branch = forms.ModelChoiceField(queryset=Branch.objects.all().order_by('name'))
    testgroups = forms.ModelMultipleChoiceField(queryset=Testgroup.objects.all().order_by('name'))

litmustojson/views.py
from django.core import serializers
from django.db import connection
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.simplejson import dumps, loads

import logging

from forms import HomeForm
from models import Product, Branch, Testgroup, Subgroup, Testcase

logger = logging.getLogger('console')

def home(request):
    if request.method == 'POST': # If the form has been submitted...
        form = HomeForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass

            # Process the data in form.cleaned_data
            # ...

            product = form.cleaned_data['product']
            branch = form.cleaned_data['branch']
            testgroups = form.cleaned_data['testgroups']

            response_data = get_response_json(product, branch, testgroups)



            # Create the HttpResponse object with the appropriate CSV header.
            response = HttpResponse(dumps(response_data), mimetype='application/json')
            response['Content-Disposition'] = 'attachment; filename=%s_litmusoutput.json' % product.name
            logger.error(response)

            return response
    else:
        logger.error('logging the request')
        logger.error(request)
        form = HomeForm() # An unbound form

    branches = Branch.objects.all().order_by('name')
    testgroups = Testgroup.objects.all().order_by('name')

    return render_to_response('home.html',
                              {'form': form,
                               'branches': branches,
                               'testgroups': testgroups
                               },
                              context_instance=RequestContext(request))

"""
Return a JSON object in the following format:
{
    "suites": [
        {
            "name": "suite name",
            "description": "suite description"
        }
    ],
    "cases": [
        {
            "name": "case name",
            "description": "case description",
            "tags": ["tag1", "tag2", "tag3"],
            "suites": ["suite1 name", "suite2 name", "suite3 name"],
            "steps": [
                {
                    "instruction": "action text",
                    "expected": "expected text"
                },
                {
                    "instruction": "action text",
                    "expected": "expected text"
                }
            ]
        }
    ]
}
"""

def get_response_json(product, branch, testgroups):
    suites = []
    for suite in testgroups:
        suites.append({
            "name": suite.name,
        })

    # get the list of subgroups for the selected testgroups.
    # Litmus' data model works that way.  No direct relation between
    # testcases and testgroups.
    subgroups = Subgroup.objects.filter(
        testgroup__in=testgroups
    ).distinct()


    cases = []

    litmus_testcases = Testcase.objects.filter(
        product = product,
        branch = branch,
        subgroup__in=subgroups).distinct()


    for litmus_case in litmus_testcases:
        tags = []
        for tag in litmus_case.subgroup.all():
            tags.append(tag.name)

        cases.append({
            "name": litmus_case.summary,
            "description": litmus_case.details or "",
            "tags": tags,
            "suites": [x.name for x in testgroups],
            "steps": [
                {
                    "instruction": litmus_case.steps,
                    "expected": litmus_case.expected_results
                }
            ]
        })


    response_data = {
        "suites": suites,
        "cases": cases
    }
    return response_data

litmustojson/templates/home.html
<head>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/screen.css" media="screen, projection" />
</head>

<div class="simple">
<h1>Litmus to JSON</h1>
<p>Start by selecting which product to migrate</p>
<form action="." method="POST">{% csrf_token %}

    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.product.errors }}
        <label for="id_product">Product:</label>
        {{ form.product }}
    </div>
    <div class="fieldWrapper">
        {{ form.branch.errors }}
        <label for="id_branch">Branch:</label>
            <select name="branch" id="id_branch">
                {% for b in branches %}
                  <option value="{{ b.branch_id }}" prod_id="{{ b.product_id }}">{{ b.name }}</option>
                {% endfor %}
            </select>
    </div>
    <div class="fieldWrapper">
        {{ form.testgroups.errors }}
        <label for="id_testgroups">Testgroups:</label>
            <select class="tall" multiple="multiple" name="testgroups" id="id_testgroups">
                {% for tg in testgroups %}
                  <option value="{{ tg.testgroup_id }}" br_id="{{ tg.branch_id }}">{{ tg.name }}</option>
                {% endfor %}
            </select>
    </div>

<input id="id_getjson"type="submit" value="Get JSON" />
</div>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.6.1.js"></script>
<script>
    $(document).ready(function() {

        function on_product_set() {

            var prod_id = $("#id_product").val();
            var options = '<option value="None">--- Select One ---</option>';

            $("#id_branch").show();
            $("#id_testgroups").hide();
            $("#id_getjson").hide();


            if ($("#id_product").val() == "") {
                $("#id_branch").hide();
                $("#id_testgroups").hide();
                $("#id_getjson").hide();

            } else {
                window.branch_options.each(function() {
                    if ($(this).attr('prod_id') == prod_id) {
                        options += '<option value="' + $(this).val() + '">' + $(this).text() + '</option>';
                    }
                });
            }

            $("#id_branch").html(options);   // populate select box with array

            // now add the change function to the branches drop-down.
            $("#id_branch").change(function() {
                var br_id = $("#id_branch").val();
                var b_opts = '';

                $("#id_testgroups").show();
                $("#id_getjson").show();

                window.testgroup_options.each(function() {
                    if ($(this).attr('br_id') == br_id) {
                        b_opts += '<option value="' + $(this).val() + '">' + $(this).text() + '</option>';
                    }

                });

                $("#id_testgroups").html(b_opts);   // populate select box with array

            });

        }

        // hide secondary elements at first
        $("#id_branch").hide();
        $("#id_testgroups").hide();
        $("#id_getjson").hide();


        // store away the options for branches
        window.branch_options = $("#id_branch").children();
        $("#id_branch").children().remove().end().append('<option selected value="None">Select Product First</option>');

        // store away the options for testgroups
        window.testgroup_options = $("#id_testgroups").children();
        $("#id_testgroups").children().remove().end().append('<option selected value="None">Select Branch First</option>');


        $("#id_product").change(on_product_set);
        on_product_set();


    });



</script>